name: Release

on: 
  push:
    branches:
      - master
      - next
      - 'rc/**'
      - 'prerelease/**'

jobs:
  release:
    runs-on: [ubuntu-latest]
    
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Environment
        uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: https://npm.pkg.github.com
          scope: '@drobenyuka'
        env:
          NODE_AUTH_TOKEN: ${{ secrets.REACT_KIT_TOKEN }}

      - name: Install dependencies and build (with cache)
        env:
          NODE_AUTH_TOKEN: ${{ secrets.REACT_KIT_TOKEN }}
        run: yarn install --frozen-lockfile

      - name: Lint
        run: yarn lint

      - name: Test
        run: yarn test --ci --coverage --maxWorkers=2

      - name: Build
        run: yarn build

      - name: Release
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            NODE_AUTH_TOKEN: ${{ secrets.REACT_KIT_TOKEN }}
        run: npx semantic-release